#!/usr/bin/env ruby

require 'octokit'
require_relative 'lib/s3_website/version'

version = S3Website::VERSION
unless ENV['S3_WEBSITE_RELEASE_KEY']
  puts "Set the S3_WEBSITE_RELEASE_KEY environmental variable. It should be your personal GitHub access token."
end

def run(cmd)
  unless system(cmd)
    exit 1
  end
end

puts "Building s3_website.jar..."
run "./sbt assembly"

tag_name = "v#{version}"
run "git tag #{tag_name} && git push origin #{tag_name}"
run "git push"

run "rake build"

client = Octokit::Client.new(:login => 'laurilehmijoki', :password => ENV['S3_WEBSITE_RELEASE_KEY'])
release = client.create_release('laurilehmijoki/s3_website', tag_name)
puts "Uploading s3_website.jar..."
client.upload_asset(release[:url], 'target/scala-2.11/s3_website.jar')
run "gem push pkg/s3_website_monadic-#{version}.gem"
